Night deprecation
MewsSystems/gitbook-distributor-guide pull request #60
Opened 2021-07-21 08:29 UTC by prazi

#### Changelog notes 

```
* Added/Extended operations....
```

#### Check during review

- [ ] JSON example extended.
  - [ ] New properties are added to the correct place in the JSON.
- [ ] New properties in the table are added to the correct place.
- [ ] Correct formatting:
  - [ ] Spacing is consistent between titles, sections, tables, ...
  - [ ] Correct JSON format - indentation.
- [ ] DateTime properties should always be defined in ISO format.

2021-07-21 09:26 UTC, koprivajakub requested changes
We need to firstly document the Services data... My recommendation is to document that part first with a changelog notice and then do the deprecation. This way the customer of the API would not know what PerTimeUnit means

2021-07-21 09:26 UTC, koprivajakub commented on distributor-api-v1/operations.md
> +            "PostingMode": "Daily",
![image](https://user-images.githubusercontent.com/6573164/126463680-b538d659-b8ec-4cc7-abfb-67bbb76d6829.png)

`PostingMode` example should be `PerTimeUnit` right?

Same thing for line 137 https://github.com/MewsSystems/gitbook-distributor-guide/pull/60/files#diff-e0d8177d43ad27101a34daf5ee1404fa5b293c8884f331abcbe852ac6671a819R137

2021-08-03 06:10 UTC, prazi commented on distributor-api-v1/changelog.md
>  ## 21.07.2021
also I realized I forgot to update the date when the PR was merged so we have the creation date in the changelog, should I change it to 08.02.2021 now? @koprivajakub

2021-08-03 14:43 UTC, koprivajakub approved these changes

2021-08-03 14:43 UTC, merged

2021-08-03 14:52 UTC, vitasamek commented on distributor-api-v1/deprecations/average-amount-per-night.md
> +`AverageAmountPerNight` field of [room price](../operations.md#room-price) object is deprecated and will be removed from the response of [hotels/getAvailability](../operations.md#get-availability) an
missing empty line.

2021-08-03 14:52 UTC, vitasamek commented on distributor-api-v1/deprecations/average-amount-per-night.md
> +`AverageAmountPerNight` field of [room price](../operations.md#room-price) object is deprecated and will be removed from the response of [hotels/getAvailability](../operations.md#get-availability) an
double dots `pricing)..`

2021-08-03 14:52 UTC, vitasamek commented on distributor-api-v1/deprecations/product-charging.md
> +`Charging` field of [product](../operations.md#product) object is deprecated and will be removed from the response of [hotels/get](../operations.md#get-hotels) and [configurations/get](../operations.
missing empty line

2021-08-03 14:52 UTC, vitasamek commented on distributor-api-v1/deprecations/product-charging.md
> +`Charging` field of [product](../operations.md#product) object is deprecated and will be removed from the response of [hotels/get](../operations.md#get-hotels) and [configurations/get](../operations.
again double dots at the end.

2021-08-03 14:52 UTC, vitasamek commented on distributor-api-v1/deprecations/product-posting.md
> +`Posting` field of [product](../operations.md#product) object is deprecated and will be removed from the response of [hotels/get](../operations.md#get-hotels) and [configurations/get](../operations.m
The same

2021-08-03 14:52 UTC, vitasamek commented on distributor-api-v1/deprecations/settlement-maximum-nights.md
> +`SettlementMaximumNights` field of [rate group](../operations.md#rate-group) object is deprecated and will be removed from the response of [hotels/getAvailability](../operations.md#get-availability).
Empty line